<?php
/**
 * Generated by Haxe 4.1.1
 * Haxe source file: /usr/share/haxe/std/haxe/io/Output.hx
 */

namespace haxe\io;

use \haxe\io\_BytesData\Container;
use \php\Boot;
use \haxe\Exception;

/**
 * An Output is an abstract write. A specific output implementation will only
 * have to override the `writeByte` and maybe the `write`, `flush` and `close`
 * methods. See `File.write` and `String.write` for two ways of creating an
 * Output.
 */
class Output {
	/**
	 * @var bool
	 * Endianness (word byte order) used when writing numbers.
	 * If `true`, big-endian is used, otherwise `little-endian` is used.
	 */
	public $bigEndian;

	/**
	 * Close the output.
	 * Behaviour while writing after calling this method is unspecified.
	 * 
	 * @return void
	 */
	public function close () {
	}

	/**
	 * Inform that we are about to write at least `nbytes` bytes.
	 * The underlying implementation can allocate proper working space depending
	 * on this information, or simply ignore it. This is not a mandatory call
	 * but a tip and is only used in some specific cases.
	 * 
	 * @param int $nbytes
	 * 
	 * @return void
	 */
	public function prepare ($nbytes) {
	}

	/**
	 * @param bool $b
	 * 
	 * @return bool
	 */
	public function set_bigEndian ($b) {
		#/usr/share/haxe/std/haxe/io/Output.hx:95: characters 3-16
		$this->bigEndian = $b;
		#/usr/share/haxe/std/haxe/io/Output.hx:96: characters 3-11
		return $b;
	}

	/**
	 * Write all bytes stored in `s`.
	 * 
	 * @param Bytes $s
	 * 
	 * @return void
	 */
	public function write ($s) {
		#/usr/share/haxe/std/haxe/io/Output.hx:104: characters 3-20
		$l = $s->length;
		#/usr/share/haxe/std/haxe/io/Output.hx:105: characters 3-13
		$p = 0;
		#/usr/share/haxe/std/haxe/io/Output.hx:106: lines 106-112
		while ($l > 0) {
			#/usr/share/haxe/std/haxe/io/Output.hx:107: characters 4-32
			$k = $this->writeBytes($s, $p, $l);
			#/usr/share/haxe/std/haxe/io/Output.hx:108: lines 108-109
			if ($k === 0) {
				#/usr/share/haxe/std/haxe/io/Output.hx:109: characters 5-10
				throw Exception::thrown(Error::Blocked());
			}
			#/usr/share/haxe/std/haxe/io/Output.hx:110: characters 4-10
			$p += $k;
			#/usr/share/haxe/std/haxe/io/Output.hx:111: characters 4-10
			$l -= $k;
		}
	}

	/**
	 * Write one byte.
	 * 
	 * @param int $c
	 * 
	 * @return void
	 */
	public function writeByte ($c) {
		#/usr/share/haxe/std/haxe/io/Output.hx:47: characters 3-8
		throw Exception::thrown("Not implemented");
	}

	/**
	 * Write `len` bytes from `s` starting by position specified by `pos`.
	 * Returns the actual length of written data that can differ from `len`.
	 * See `writeFullBytes` that tries to write the exact amount of specified bytes.
	 * 
	 * @param Bytes $s
	 * @param int $pos
	 * @param int $len
	 * 
	 * @return int
	 */
	public function writeBytes ($s, $pos, $len) {
		#/usr/share/haxe/std/haxe/io/Output.hx:59: lines 59-60
		if (($pos < 0) || ($len < 0) || (($pos + $len) > $s->length)) {
			#/usr/share/haxe/std/haxe/io/Output.hx:60: characters 4-9
			throw Exception::thrown(Error::OutsideBounds());
		}
		#/usr/share/haxe/std/haxe/io/Output.hx:62: characters 3-61
		$b = $s->b;
		#/usr/share/haxe/std/haxe/io/Output.hx:63: characters 3-15
		$k = $len;
		#/usr/share/haxe/std/haxe/io/Output.hx:64: lines 64-78
		while ($k > 0) {
			#/usr/share/haxe/std/haxe/io/Output.hx:68: characters 4-25
			$this->writeByte(ord($b->s[$pos]));
			#/usr/share/haxe/std/haxe/io/Output.hx:76: characters 4-9
			++$pos;
			#/usr/share/haxe/std/haxe/io/Output.hx:77: characters 4-7
			--$k;
		}
		#/usr/share/haxe/std/haxe/io/Output.hx:79: characters 3-13
		return $len;
	}

	/**
	 * Write `len` bytes from `s` starting by position specified by `pos`.
	 * Unlike `writeBytes`, this method tries to write the exact `len` amount of bytes.
	 * 
	 * @param Bytes $s
	 * @param int $pos
	 * @param int $len
	 * 
	 * @return void
	 */
	public function writeFullBytes ($s, $pos, $len) {
		#/usr/share/haxe/std/haxe/io/Output.hx:121: lines 121-125
		while ($len > 0) {
			#/usr/share/haxe/std/haxe/io/Output.hx:122: characters 4-36
			$k = $this->writeBytes($s, $pos, $len);
			#/usr/share/haxe/std/haxe/io/Output.hx:123: characters 4-12
			$pos += $k;
			#/usr/share/haxe/std/haxe/io/Output.hx:124: characters 4-12
			$len -= $k;
		}
	}

	/**
	 * Write `s` string.
	 * 
	 * @param string $s
	 * @param Encoding $encoding
	 * 
	 * @return void
	 */
	public function writeString ($s, $encoding = null) {
		#/usr/share/haxe/std/haxe/io/Output.hx:282: characters 11-38
		$b = strlen($s);
		#/usr/share/haxe/std/haxe/io/Output.hx:282: characters 3-39
		$b1 = new Bytes($b, new Container($s));
		#/usr/share/haxe/std/haxe/io/Output.hx:284: characters 3-33
		$this->writeFullBytes($b1, 0, $b1->length);
	}
}

Boot::registerClass(Output::class, 'haxe.io.Output');
Boot::registerSetters('haxe\\io\\Output', [
	'bigEndian' => true
]);
