<?php
/**
 * Generated by Haxe 4.1.1
 * Haxe source file: src/model/roles/Users.hx
 */

namespace model\roles;

use \php\_Boot\HxAnon;
use \php\Boot;
use \haxe\Log;
use \haxe\ds\StringMap;

/**
 * ...
 * @author axel@bi4.me
 */
class Users extends \Model {
	/**
	 * @param StringMap $param
	 * 
	 * @return void
	 */
	public static function _create ($param) {
		#src/model/roles/Users.hx:13: characters 3-37
		$self = new Users($param);
	}

	/**
	 * @param StringMap $param
	 * 
	 * @return void
	 */
	public function __construct ($param = null) {
		#src/model/roles/Users.hx:9: lines 9-23
		parent::__construct($param);
	}

	/**
	 * @return void
	 */
	public function list () {
		#src/model/roles/Users.hx:19: characters 3-8
		(Log::$trace)(($this->param === null ? "null" : $this->param->toString()), new HxAnon([
			"fileName" => "src/model/roles/Users.hx",
			"lineNumber" => 19,
			"className" => "model.roles.Users",
			"methodName" => "list",
		]));
		#src/model/roles/Users.hx:20: characters 3-8
		$this->get();
	}
}

Boot::registerClass(Users::class, 'model.roles.Users');
