<?php
/**
 * Generated by Haxe 4.1.1
 * Haxe source file: /usr/share/haxe/std/haxe/Constraints.hx
 */

namespace haxe;

use \php\Boot;

interface IMap {
	/**
	 * @param mixed $k
	 * 
	 * @return mixed
	 */
	public function get ($k) ;

	/**
	 * @return object
	 */
	public function keys () ;

	/**
	 * @return string
	 */
	public function toString () ;
}

Boot::registerClass(IMap::class, 'haxe.IMap');
