<?php
/**
 * Generated by Haxe 4.1.1
 * Haxe source file: /usr/share/haxe/std/haxe/CallStack.hx
 */

namespace haxe\_CallStack;

use \php\Boot;
use \haxe\NativeStackTrace;

final class CallStack_Impl_ {
	/**
	 * Return the call stack elements, or an empty array if not available.
	 * 
	 * @return \Array_hx
	 */
	public static function callStack () {
		#/usr/share/haxe/std/haxe/CallStack.hx:52: characters 3-63
		return NativeStackTrace::toHaxe(debug_backtrace(DEBUG_BACKTRACE_IGNORE_ARGS));
	}
}

Boot::registerClass(CallStack_Impl_::class, 'haxe._CallStack.CallStack_Impl_');
