<?php
/**
 * Generated by Haxe 4.1.1
 * Haxe source file: /opt/src/crm-2.0/server/.haxelib/hxbit/1,5,0/hxbit/Convert.hx
 */

namespace hxbit;

use \php\Boot;

class ConvertField {
	/**
	 * @var \Closure
	 */
	public $conv;
	/**
	 * @var mixed
	 */
	public $defaultValue;
	/**
	 * @var PropTypeDesc
	 */
	public $from;
	/**
	 * @var int
	 */
	public $index;
	/**
	 * @var string
	 */
	public $path;
	/**
	 * @var bool
	 */
	public $same;
	/**
	 * @var PropTypeDesc
	 */
	public $to;

	/**
	 * @param string $path
	 * @param PropTypeDesc $from
	 * @param PropTypeDesc $to
	 * 
	 * @return void
	 */
	public function __construct ($path, $from, $to) {
		#/opt/src/crm-2.0/server/.haxelib/hxbit/1,5,0/hxbit/Convert.hx:33: characters 3-19
		$this->path = $path;
		#/opt/src/crm-2.0/server/.haxelib/hxbit/1,5,0/hxbit/Convert.hx:34: characters 3-19
		$this->from = $from;
		#/opt/src/crm-2.0/server/.haxelib/hxbit/1,5,0/hxbit/Convert.hx:35: characters 3-15
		$this->to = $to;
	}
}

Boot::registerClass(ConvertField::class, 'hxbit.ConvertField');
