<?php
/**
 * Generated by Haxe 4.1.1
 * Haxe source file: /opt/src/crm-2.0/server/.haxelib/hxbit/1,5,0/hxbit/Serializable.hx
 */

namespace hxbit;

use \php\Boot;

interface Serializable {
	/**
	 * Returns the unique class id for this object
	 * 
	 * @return int
	 */
	public function getCLID () ;

	/**
	 * Returns the object data schema
	 * 
	 * @return Schema
	 */
	public function getSerializeSchema () ;

	/**
	 * Serialize the object id and fields using this Serializer
	 * 
	 * @param Serializer $ctx
	 * 
	 * @return void
	 */
	public function serialize ($ctx) ;

	/**
	 * Unserialize object fields using this Serializer
	 * 
	 * @param Serializer $ctx
	 * 
	 * @return void
	 */
	public function unserialize ($ctx) ;

	/**
	 * Used internaly by unserializer
	 * 
	 * @return void
	 */
	public function unserializeInit () ;
}

Boot::registerClass(Serializable::class, 'hxbit.Serializable');
