<?php
/**
 * Generated by Haxe 4.1.1
 * Haxe source file: /usr/share/haxe/std/php/_std/haxe/crypto/Sha256.hx
 */

namespace haxe\crypto;

use \haxe\io\_BytesData\Container;
use \php\Boot;
use \haxe\io\Bytes;

class Sha256 {
	/**
	 * @param Bytes $b
	 * 
	 * @return Bytes
	 */
	public static function make ($b) {
		#/usr/share/haxe/std/php/_std/haxe/crypto/Sha256.hx:34: characters 10-64
		$b1 = new Container(hash("sha256", $b->b->s, true));
		return new Bytes(strlen($b1->s), $b1);
	}
}

Boot::registerClass(Sha256::class, 'haxe.crypto.Sha256');
