<?php
/**
 * Generated by Haxe 4.1.1
 * Haxe source file: /usr/share/haxe/std/php/Lib.hx
 */

namespace php;

use \php\_Boot\HxAnon;
use \haxe\ds\StringMap;

/**
 * Platform-specific PHP Library. Provides some platform-specific functions
 * for the PHP target, such as conversion from Haxe types to native types
 * and vice-versa.
 */
class Lib {
	/**
	 * @param mixed $arr
	 * 
	 * @return StringMap
	 */
	public static function hashOfAssociativeArray ($arr) {
		#/usr/share/haxe/std/php/Lib.hx:102: characters 3-32
		$result = new StringMap();
		#/usr/share/haxe/std/php/Lib.hx:103: characters 19-36
		$result->data = $arr;
		#/usr/share/haxe/std/php/Lib.hx:104: characters 3-16
		return $result;
	}

	/**
	 * @param mixed $arr
	 * 
	 * @return mixed
	 */
	public static function objectOfAssociativeArray ($arr) {
		#/usr/share/haxe/std/php/Lib.hx:112: lines 112-116
		foreach ($arr as $key => $value) {
			#/usr/share/haxe/std/php/Lib.hx:113: lines 113-115
			$value1 = $value;
			if (is_array($value1)) {
				#/usr/share/haxe/std/php/Lib.hx:114: characters 5-47
				$arr[$key] = Lib::objectOfAssociativeArray($value1);
			}
		}
		#/usr/share/haxe/std/php/Lib.hx:117: characters 3-30
		return new HxAnon($arr);
	}

	/**
	 * Print the specified value on the default output followed by
	 * a newline character.
	 * 
	 * @param mixed $v
	 * 
	 * @return void
	 */
	public static function println ($v) {
		#/usr/share/haxe/std/php/Lib.hx:47: characters 3-11
		echo(\Std::string($v));
		#/usr/share/haxe/std/php/Lib.hx:48: characters 3-14
		echo("\x0A");
	}
}

Boot::registerClass(Lib::class, 'php.Lib');
