<?php
/**
 * Generated by Haxe 4.0.0-rc.5+4a745347f
 * Haxe source file: /usr/share/haxe/std/php/Boot.hx
 */

namespace php\_Boot;

use \php\Boot;

/**
 * Special exception which is used to wrap non-throwable values
 */
class HxException extends \Exception {
	/**
	 * @var mixed
	 */
	public $e;

	/**
	 * @param mixed $e
	 * 
	 * @return void
	 */
	public function __construct ($e) {
		#/usr/share/haxe/std/php/Boot.hx:1013: characters 3-13
		$this->e = $e;
		#/usr/share/haxe/std/php/Boot.hx:1014: characters 3-27
		parent::__construct(Boot::stringify($e));
	}
}

Boot::registerClass(HxException::class, 'php._Boot.HxException');
