<?php
/**
 * Generated by Haxe 4.1.1
 * Haxe source file: /opt/src/crm-2.0/server/.haxelib/tjson/1,4,0/tjson/TJSON.hx
 */

namespace tjson;

use \php\Boot;

class FancyStyle implements EncodeStyle {
	/**
	 * @var \Array_hx
	 */
	public $charTimesNCache;
	/**
	 * @var string
	 */
	public $tab;

	/**
	 * @param string $tab
	 * 
	 * @return void
	 */
	public function __construct ($tab = "    ") {
		#/opt/src/crm-2.0/server/.haxelib/tjson/1,4,0/tjson/TJSON.hx:558: lines 558-561
		if ($tab === null) {
			$tab = "    ";
		}
		#/opt/src/crm-2.0/server/.haxelib/tjson/1,4,0/tjson/TJSON.hx:559: characters 3-17
		$this->tab = $tab;
		#/opt/src/crm-2.0/server/.haxelib/tjson/1,4,0/tjson/TJSON.hx:560: characters 3-25
		$this->charTimesNCache = \Array_hx::wrap([""]);
	}

	/**
	 * @param int $depth
	 * 
	 * @return string
	 */
	public function beginArray ($depth) {
		#/opt/src/crm-2.0/server/.haxelib/tjson/1,4,0/tjson/TJSON.hx:569: characters 3-15
		return "[\x0A";
	}

	/**
	 * @param int $depth
	 * 
	 * @return string
	 */
	public function beginObject ($depth) {
		#/opt/src/crm-2.0/server/.haxelib/tjson/1,4,0/tjson/TJSON.hx:563: characters 3-15
		return "{\x0A";
	}

	/**
	 * @param int $n
	 * 
	 * @return string
	 */
	public function charTimesN ($n) {
		#/opt/src/crm-2.0/server/.haxelib/tjson/1,4,0/tjson/TJSON.hx:585: lines 585-589
		if ($n < $this->charTimesNCache->length) {
			#/opt/src/crm-2.0/server/.haxelib/tjson/1,4,0/tjson/TJSON.hx:586: characters 4-22
			return ($this->charTimesNCache->arr[$n] ?? null);
		} else {
			#/opt/src/crm-2.0/server/.haxelib/tjson/1,4,0/tjson/TJSON.hx:588: characters 25-40
			$tmp = $this->charTimesN($n - 1);
			#/opt/src/crm-2.0/server/.haxelib/tjson/1,4,0/tjson/TJSON.hx:588: characters 4-46
			return $this->charTimesNCache->offsetSet($n, ($tmp??'null') . ($this->tab??'null'));
		}
	}

	/**
	 * @param int $depth
	 * 
	 * @return string
	 */
	public function endArray ($depth) {
		#/opt/src/crm-2.0/server/.haxelib/tjson/1,4,0/tjson/TJSON.hx:572: characters 3-36
		return "\x0A" . ($this->charTimesN($depth)??'null') . "]";
	}

	/**
	 * @param int $depth
	 * 
	 * @return string
	 */
	public function endObject ($depth) {
		#/opt/src/crm-2.0/server/.haxelib/tjson/1,4,0/tjson/TJSON.hx:566: characters 3-36
		return "\x0A" . ($this->charTimesN($depth)??'null') . "}";
	}

	/**
	 * @param int $depth
	 * 
	 * @return string
	 */
	public function entrySeperator ($depth) {
		#/opt/src/crm-2.0/server/.haxelib/tjson/1,4,0/tjson/TJSON.hx:578: characters 3-38
		return "\x0A" . ($this->charTimesN($depth + 1)??'null') . ",";
	}

	/**
	 * @param int $depth
	 * 
	 * @return string
	 */
	public function firstEntry ($depth) {
		#/opt/src/crm-2.0/server/.haxelib/tjson/1,4,0/tjson/TJSON.hx:575: characters 3-33
		return ($this->charTimesN($depth + 1)??'null') . " ";
	}

	/**
	 * @param int $depth
	 * 
	 * @return string
	 */
	public function keyValueSeperator ($depth) {
		#/opt/src/crm-2.0/server/.haxelib/tjson/1,4,0/tjson/TJSON.hx:581: characters 3-15
		return " : ";
	}
}

Boot::registerClass(FancyStyle::class, 'tjson.FancyStyle');
