<?php
/**
 * Generated by Haxe 4.1.1
 * Haxe source file: /opt/src/crm-2.0/server/.haxelib/tjson/1,4,0/tjson/TJSON.hx
 */

namespace tjson;

use \php\Boot;

class SimpleStyle implements EncodeStyle {
	/**
	 * @return void
	 */
	public function __construct () {
	}

	/**
	 * @param int $depth
	 * 
	 * @return string
	 */
	public function beginArray ($depth) {
		#/opt/src/crm-2.0/server/.haxelib/tjson/1,4,0/tjson/TJSON.hx:538: characters 3-13
		return "[";
	}

	/**
	 * @param int $depth
	 * 
	 * @return string
	 */
	public function beginObject ($depth) {
		#/opt/src/crm-2.0/server/.haxelib/tjson/1,4,0/tjson/TJSON.hx:532: characters 3-13
		return "{";
	}

	/**
	 * @param int $depth
	 * 
	 * @return string
	 */
	public function endArray ($depth) {
		#/opt/src/crm-2.0/server/.haxelib/tjson/1,4,0/tjson/TJSON.hx:541: characters 3-13
		return "]";
	}

	/**
	 * @param int $depth
	 * 
	 * @return string
	 */
	public function endObject ($depth) {
		#/opt/src/crm-2.0/server/.haxelib/tjson/1,4,0/tjson/TJSON.hx:535: characters 3-13
		return "}";
	}

	/**
	 * @param int $depth
	 * 
	 * @return string
	 */
	public function entrySeperator ($depth) {
		#/opt/src/crm-2.0/server/.haxelib/tjson/1,4,0/tjson/TJSON.hx:547: characters 3-13
		return ",";
	}

	/**
	 * @param int $depth
	 * 
	 * @return string
	 */
	public function firstEntry ($depth) {
		#/opt/src/crm-2.0/server/.haxelib/tjson/1,4,0/tjson/TJSON.hx:544: characters 3-12
		return "";
	}

	/**
	 * @param int $depth
	 * 
	 * @return string
	 */
	public function keyValueSeperator ($depth) {
		#/opt/src/crm-2.0/server/.haxelib/tjson/1,4,0/tjson/TJSON.hx:550: characters 3-13
		return ":";
	}
}

Boot::registerClass(SimpleStyle::class, 'tjson.SimpleStyle');
