<?php
/**
 * Generated by Haxe 4.1.1
 * Haxe source file: src/model/data/Accounts.hx
 */

namespace model\data;

use \php\_Boot\HxAnon;
use \php\Boot;
use \haxe\Log;
use \haxe\ds\StringMap;

class Accounts extends \Model {
	/**
	 * @param StringMap $param
	 * 
	 * @return void
	 */
	public function __construct ($param = null) {
		#src/model/data/Accounts.hx:9: characters 3-15
		parent::__construct($param);
		#src/model/data/Accounts.hx:10: characters 3-7
		$this->go();
	}

	/**
	 * @return void
	 */
	public function go () {
		#src/model/data/Accounts.hx:14: characters 3-8
		(Log::$trace)($this->action, new HxAnon([
			"fileName" => "src/model/data/Accounts.hx",
			"lineNumber" => 14,
			"className" => "model.data.Accounts",
			"methodName" => "go",
		]));
		#src/model/data/Accounts.hx:15: characters 10-16
		$_g = $this->action;
		#src/model/data/Accounts.hx:17: characters 5-10
		$this->run();
	}
}

Boot::registerClass(Accounts::class, 'model.data.Accounts');
