<?php
/**
 * Generated by Haxe 4.1.1
 * Haxe source file: /opt/src/lib/me/cunity/debug/Out.hx
 */

namespace me\cunity\debug;

use \php\Boot;
use \php\_Boot\HxEnum;

class DebugOutput extends HxEnum {
	/**
	 * @return DebugOutput
	 */
	static public function CONSOLE () {
		static $inst = null;
		if (!$inst) $inst = new DebugOutput('CONSOLE', 0, []);
		return $inst;
	}

	/**
	 * @return DebugOutput
	 */
	static public function HAXE () {
		static $inst = null;
		if (!$inst) $inst = new DebugOutput('HAXE', 1, []);
		return $inst;
	}

	/**
	 * @return DebugOutput
	 */
	static public function NATIVE () {
		static $inst = null;
		if (!$inst) $inst = new DebugOutput('NATIVE', 2, []);
		return $inst;
	}

	/**
	 * Returns array of (constructorIndex => constructorName)
	 *
	 * @return string[]
	 */
	static public function __hx__list () {
		return [
			0 => 'CONSOLE',
			1 => 'HAXE',
			2 => 'NATIVE',
		];
	}

	/**
	 * Returns array of (constructorName => parametersCount)
	 *
	 * @return int[]
	 */
	static public function __hx__paramsCount () {
		return [
			'CONSOLE' => 0,
			'HAXE' => 0,
			'NATIVE' => 0,
		];
	}
}

Boot::registerClass(DebugOutput::class, 'me.cunity.debug.DebugOutput');
